define([], function () {
  return {
      "WebPartPropertyGroupAbout": "About",
      "WebPartPropertyGroupGreetings": "Greeting",
      "WebPartManageGreetingTextButtonText": "Manage Greeting text",
      "SaveLabel": "Save",
      "CancelLabel": "Cancel",
      "AddLabel": "Add",
      "GreetingTextLabel": "Greeting text",
      "FromHourLabel": "From hour",
      "FromMinuteLabel": "From minute",
      "ToHourLabel": "To hour",
      "ToMinuteLabel": "To minute",
      "CUSTOM_HeaderNormalText": "Normal text",
      "CUSTOM_HeaderH2": "Heading 1",
      "CUSTOM_HeaderH3": "Heading 2",
      "CUSTOM_HeaderH4": "Heading 3",
      "CUSTOM_HeaderBlockQuote": "Pull quote",
      "CUSTOM_AlignLeft": "Align left",
      "CUSTOM_AlignCenter": "Center",
      "CUSTOM_AlignRight": "Align right",
      "CUSTOM_AlignJustify": "Justify",
      "CUSTOM_ListBullet": "Bulleted list",
      "CUSTOM_ListNumbered": "Numbered list",
      "CUSTOM_StyleTitle": "Style",
      "CUSTOM_BoldTitle": "Bold (Ctrl+B)",
      "CUSTOM_ItalicTitle": "Italic (Ctrl+I)",
      "CUSTOM_UnderlineTitle": "Underline (Ctrl+U)",
      "CUSTOM_AlignTitle": "Align",
      "CUSTOM_ListTitle": "List",
      "CUSTOM_LinkTitle": "Hyperlink",
      "CUSTOM_ImageTitle": "Image",
      "CUSTOM_MoreTitle": "More",
      "CUSTOM_FormattingPaneTitle": "Text formatting",
      "CUSTOM_CloseButton": "Close",
      "CUSTOM_InsertLinkTitle": "Insert link",
      "CUSTOM_InsertImageTitle": "Insert image",
      "CUSTOM_AddressFieldLabel": "Address",
      "CUSTOM_TextToDisplayLabel": "Text to display",
      "CUSTOM_SaveButtonLabel": "Save",
      "CUSTOM_CancelButtonLabel": "Cancel",
      "CUSTOM_RemoveLinkLabel": "Remove link",
      "CUSTOM_ParagraphSectionTitle": "Paragraph",
      "CUSTOM_HyperlinkSectionTitle": "Hyperlink",
      "CUSTOM_UndoTitle": "Undo (Ctrl+Z)",
      "CUSTOM_RedoTitle": "Redo (Ctrl+Y)",
      "CUSTOM_ClearFormattingTitle": "Clear all formatting",
      "CUSTOM_FontStyleTitle": "Font style",
      "CUSTOM_FontSizeTitle": "Font size",
      "CUSTOM_StrikethroughTitle": "Strikethrough",
      "CUSTOM_SuperscriptTitle": "Superscript",
      "CUSTOM_SubscriptTitle": "Subscript",
      "CUSTOM_FontColorLabel": "Font Color",
      "CUSTOM_AutomaticFontColor": "Automatic",
      "CUSTOM_HighlightColorLabel": "Highlight color",
      "CUSTOM_NoColorHighlightColor": "No color",
      "CUSTOM_IncreaseIndentTitle": "Increase indent",
      "CUSTOM_DecreaseIndentTitle": "Decrease indent",
      "CUSTOM_ThemeColorsGroupName": "Theme colors",
      "CUSTOM_HighlightColorsGroupName": "Highlight colors",
      "CUSTOM_StandardColorsGroupName": "Standard colors",
      "CUSTOM_CustomColorsGroupName": "Custom Colors",
      "CUSTOM_ThemeColorDarker": "Theme darker",
      "CUSTOM_ThemeColorDark": "Theme dark",
      "CUSTOM_ThemeColorDarkAlt": "Theme dark alternate",
      "CUSTOM_ThemeColorPrimary": "Theme primary",
      "CUSTOM_ThemeColorSecondary": "Theme secondary",
      "CUSTOM_ThemeColorTertiary": "Neutral tertiary",
      "CUSTOM_ThemeColorNeutralSecondary": "Neutral secondary",
      "CUSTOM_ThemeColorNeutralPrimaryAlt": "Neutral primary alternate",
      "CUSTOM_ThemeColorNeutralPrimary": "Neutral primary",
      "CUSTOM_ThemeColorNeutralDark": "Neutral dark",
      "CUSTOM_HighlightColorYellow": "Yellow",
      "CUSTOM_HighlightColorGreen": "Green",
      "CUSTOM_HighlightColorAqua": "Aqua",
      "CUSTOM_HighlightColorMagenta": "Magenta",
      "CUSTOM_HighlightColorBlue": "Blue",
      "CUSTOM_HighlightColorRed": "Red",
      "CUSTOM_HighlightColorDarkblue": "Dark blue",
      "CUSTOM_HighlightColorTeal": "Teal",
      "CUSTOM_HighlightColorDarkgreen": "Dark green",
      "CUSTOM_HighlightColorPurple": "Purple",
      "CUSTOM_HighlightColorMaroon": "Maroon",
      "CUSTOM_HighlightColorGold": "Gold",
      "CUSTOM_HighlightColorDarkgrey": "Dark grey",
      "CUSTOM_HighlightColorGrey": "Grey",
      "CUSTOM_HighlightColorBlack": "Black",
      "CUSTOM_StandardColorDarkred": "Dark red",
      "CUSTOM_StandardColorRed": "Red",
      "CUSTOM_StandardColorOrange": "Orange",
      "CUSTOM_StandardColorYellow": "Yellow",
      "CUSTOM_StandardColorLightgreen": "Light green",
      "CUSTOM_StandardColorGreen": "Green",
      "CUSTOM_StandardColorLightblue": "Light blue",
      "CUSTOM_StandardColorBlue": "Blue",
      "CUSTOM_StandardColorDarkblue": "Dark blue",
      "CUSTOM_StandardColorPurple": "Purple"
  };
});